//
// FILE            pluginLoader.c
//
// AUTHOR          Ken Zangelin
//
// Copyright 2026 Seamware
// SPDX-License-Identifier: Apache-2.0
//

#include <stdio.h>                                    // snprintf
#include <string.h>                                   // memset, strcmp, strncpy, strchr, strtok_r
#include <stdlib.h>                                   // qsort
#include <unistd.h>                                   // access
#include <dlfcn.h>                                    // dlopen, dlsym, dlclose, RTLD_NOLOAD

#include "corPlugin/corPlugin.h"                        // corPluginOpen, corPluginCloseAll, corPluginResolve, corPluginBaseDir, corPluginArgUpdate
#include "corArgs/corArgs.h"                          // corArgsAdd, corArgsStatus, CorArg, CORARGS_SEPARATOR, CORARGS_END
#include "corArgs/corArgsInit.h"                      // corArgInfoV
#include "corLog/corLog.h"                            // COR_I, COR_X

#include "db/DbDriver.h"                              // DbDriver, DbRegisterFunc, db
#include "troe/TroeDriver.h"                          // TroeDriver, TroeRegisterFunc, troe
#include "plugin/ApiPlugin.h"                         // ApiPlugin, ApiRegisterFunc, apiPlugins
#include "corBridge/BridgeDriver.h"                   // BridgeDriver, BridgeRegisterFunc, BRIDGES_MAX
#include "plugin/pluginLoader.h"                      // Own interface
#include "dbAbiStamp.h"                               // DB_ABI_STAMP - generated by tools/dbAbiStamp.sh



// -----------------------------------------------------------------------------
//
// apiPlugins / apiPluginCount - global registry
//
ApiPlugin  apiPlugins[API_PLUGINS_MAX];
int        apiPluginCount = 0;



// -----------------------------------------------------------------------------
//
// bridges / bridgeCount - global registry
//
BridgeDriver  bridges[BRIDGES_MAX];
int           bridgeCount = 0;



// -----------------------------------------------------------------------------
//
// coraineDbAbi - the DB / TRoE plugin interface stamp this broker was built with (tools/dbAbiStamp.sh)
//
// Exported (the broker is linked -rdynamic): every DB / TRoE plugin looks it up in its register function
// and refuses a broker without it or with another (src/plugins/shared/dbPluginAbi.c). A char array, so
// the symbol's address IS the string.
//
__attribute__((visibility("default"), used)) const char coraineDbAbi[] = DB_ABI_STAMP;



// -----------------------------------------------------------------------------
//
// pluginAbiCheck - the plugin's interface stamp (dbPluginAbi) against this broker's: false on a mismatch
//
// After the dlopen and BEFORE the register function: a plugin built against another DbDriver /
// DbQueryFilter / TroeDriver ... reads and writes the broker's structs at the wrong offsets - a plugin
// built before seek fields were appended to DbQueryFilter read past the broker's struct and wrote past it
// - so it is refused, not tolerated. A plugin without the symbol was built before the check, and is
// refused as well: nothing says what it was built against.
//
// The plugin is open already (corPluginOpen): RTLD_NOLOAD finds that handle, and dlsym on it searches the
// plugin and its dependencies - not the broker.
//
static bool pluginAbiCheck(const char* kind, const char* path, char* errorBuf, int errorBufSize)
{
  void*        handle      = dlopen(path, RTLD_NOW | RTLD_NOLOAD);
  const char*  pluginStamp = (handle != NULL) ? (const char*) dlsym(handle, "dbPluginAbi") : NULL;
  bool         ok          = (pluginStamp != NULL) && (strcmp(pluginStamp, coraineDbAbi) == 0);

  if ((ok == false) && (errorBuf != NULL))
    snprintf(errorBuf, errorBufSize,
             "%s plugin '%s' does not match this broker: %s; a plugin built against another DB plugin interface corrupts memory\n"
             "  plugin's interface stamp: %.32s\n"
             "  broker's interface stamp: %s\n"
             "  rebuild the plugin against this broker's source, or install matching versions of the broker and its plugins",
             kind, path,
             (pluginStamp == NULL) ? "it has no DB plugin interface stamp" : "it was built against another DB plugin interface",
             (pluginStamp != NULL) ? pluginStamp : "none - built before the check",
             coraineDbAbi);

  if (handle != NULL)
    dlclose(handle);                                  // the reference RTLD_NOLOAD took - corPluginOpen keeps its own

  return ok;
}



// -----------------------------------------------------------------------------
//
// pluginLoadDb - load a DB plugin
//
int pluginLoadDb(const char* shortName, char* errorBuf, int errorBufSize)
{
  char path[512];

  memset(&db, 0, sizeof(DbDriver));

  corPluginResolve(corPluginBaseDir(), "db", "currentState", shortName, path, sizeof(path));

  char openErr[512];
  DbRegisterFunc registerFunc = (DbRegisterFunc) corPluginOpen(path, "dbRegister", openErr, sizeof(openErr));
  if (registerFunc == NULL)
  {
    if (errorBuf != NULL)
    {
      if (strchr(shortName, '/') == NULL)
        snprintf(errorBuf, errorBufSize, "DB plugin '%s' (%s): %s", shortName, path, openErr);
      else
        snprintf(errorBuf, errorBufSize, "DB plugin '%s': %s", shortName, openErr);
    }
    return -1;
  }

  if (pluginAbiCheck("DB", path, errorBuf, errorBufSize) == false)
    return -1;

  registerFunc(&db);

  COR_I("db plugin loaded: %s", path);
  return 0;
}



// -----------------------------------------------------------------------------
//
// pluginLoadApi - load API plugins from a comma-separated list
//
int pluginLoadApi(const char* commaList, char* errorBuf, int errorBufSize)
{
  if (commaList == NULL)
    return 0;

  // Work on a copy (strtok_r modifies the string)
  char buf[1024];
  strncpy(buf, commaList, sizeof(buf) - 1);
  buf[sizeof(buf) - 1] = '\0';

  char* saveptr = NULL;
  char* token   = strtok_r(buf, ",", &saveptr);

  while (token != NULL)
  {
    // Strip leading whitespace
    while (*token == ' ')
      token++;

    if (*token == '\0')
    {
      token = strtok_r(NULL, ",", &saveptr);
      continue;
    }

    if (apiPluginCount >= API_PLUGINS_MAX)
    {
      if (errorBuf != NULL)
        snprintf(errorBuf, errorBufSize, "too many API plugins (max %d)", API_PLUGINS_MAX);
      return -1;
    }

    char path[512];
    corPluginResolve(corPluginBaseDir(), "api", NULL, token, path, sizeof(path));

    char openErr[512];
    ApiRegisterFunc registerFunc = (ApiRegisterFunc) corPluginOpen(path, "apiRegister", openErr, sizeof(openErr));
    if (registerFunc == NULL)
    {
      if (errorBuf != NULL)
      {
        if (strchr(token, '/') == NULL)
          snprintf(errorBuf, errorBufSize, "API plugin '%s' (%s): %s", token, path, openErr);
        else
          snprintf(errorBuf, errorBufSize, "API plugin '%s': %s", token, openErr);
      }
      return -1;
    }

    ApiPlugin* pluginP = &apiPlugins[apiPluginCount];
    memset(pluginP, 0, sizeof(ApiPlugin));

    registerFunc(pluginP);
    apiPluginCount++;

    COR_I("api plugin loaded: %s (alias: %s)", path, pluginP->alias ? pluginP->alias : token);

    token = strtok_r(NULL, ",", &saveptr);
  }

  return 0;
}



// -----------------------------------------------------------------------------
//
// pluginLoadTroe - load a TRoE plugin
//
int pluginLoadTroe(const char* shortName, char* errorBuf, int errorBufSize)
{
  char path[512];

  memset(&troe, 0, sizeof(TroeDriver));

  //
  // --troe corDB is not a plugin of its own: corDB keeps history in its store - the same lock, the same
  // log - so the TRoE driver is the current-state plugin's own troeRegister. Which needs that plugin to
  // BE corDB; another store's history goes to an external server (timescale).
  //
  if (strcmp(shortName, "corDB") == 0)
  {
    if ((db.alias == NULL) || (strcmp(db.alias, "corDB") != 0))
    {
      if (errorBuf != NULL)
        snprintf(errorBuf, errorBufSize, "TRoE 'corDB' keeps the history inside the corDB store - it needs --database corDB (not '%s')", (db.alias != NULL) ? db.alias : "?");
      return -1;
    }

    corPluginResolve(corPluginBaseDir(), "db", "currentState", "corDB", path, sizeof(path));
  }
  else
    corPluginResolve(corPluginBaseDir(), "troe", "temporal", shortName, path, sizeof(path));

  char openErr[512];
  TroeRegisterFunc registerFunc = (TroeRegisterFunc) corPluginOpen(path, "troeRegister", openErr, sizeof(openErr));
  if (registerFunc == NULL)
  {
    if (errorBuf != NULL)
    {
      if (strchr(shortName, '/') == NULL)
        snprintf(errorBuf, errorBufSize, "TRoE plugin '%s' (%s): %s", shortName, path, openErr);
      else
        snprintf(errorBuf, errorBufSize, "TRoE plugin '%s': %s", shortName, openErr);
    }
    return -1;
  }

  if (pluginAbiCheck("TRoE", path, errorBuf, errorBufSize) == false)
    return -1;

  registerFunc(&troe);

  COR_I("troe plugin loaded: %s", path);
  return 0;
}



// -----------------------------------------------------------------------------
//
// pluginTroeArgUpdate -
//
static int nameCompare(const void* a, const void* b)
{
  return strcmp(*(const char* const*) a, *(const char* const*) b);
}

void pluginTroeArgUpdate(void)
{
  corPluginArgUpdate("--troe", "troe/temporal");

  char path[512];
  corPluginResolve(corPluginBaseDir(), "db", "currentState", "corDB", path, sizeof(path));
  if (access(path, R_OK) != 0)
    return;                                          // no corDB: no --troe corDB either

  for (int i = 0; corArgInfoV[i].type != CorArgEnd; i++)
  {
    if ((corArgInfoV[i].longName == NULL) || (strcmp(corArgInfoV[i].longName, "--troe") != 0))
      continue;

    static char  buf[256];
    char         copy[256];
    const char*  nameV[32];
    int          names = 0;
    bool         haveCorDB = false;

    snprintf(copy, sizeof(copy), "%s", (corArgInfoV[i].description != NULL) ? corArgInfoV[i].description : "");

    char* saveP = NULL;
    for (char* nameP = strtok_r(copy, "|", &saveP); (nameP != NULL) && (names < 31); nameP = strtok_r(NULL, "|", &saveP))
    {
      if (strcmp(nameP, "corDB") == 0)
        haveCorDB = true;
      nameV[names++] = nameP;
    }

    if (haveCorDB == false)
      nameV[names++] = "corDB";

    qsort(nameV, names, sizeof(nameV[0]), nameCompare);

    buf[0] = 0;
    for (int n = 0; n < names; n++)
    {
      if (n > 0)
        strncat(buf, "|", sizeof(buf) - strlen(buf) - 1);
      strncat(buf, nameV[n], sizeof(buf) - strlen(buf) - 1);
    }

    corArgInfoV[i].description = buf;
    return;
  }
}



// -----------------------------------------------------------------------------
//
// pluginLoadBridges - load bridge plugins from a comma-separated list
//
// Bridges are the transports over which the broker speaks to something that is
// not an NGSI-LD client - a DDS topic, an MQTT broker. Like API plugins and
// unlike the DB and TRoE drivers, ANY NUMBER may be active at once: a
// deployment that bridges both DDS and MQTT loads both.
//
// This only loads the .so and lets it fill in its BridgeDriver. Bringing the
// transport up is init()'s job, and that happens later, once the broker has
// somewhere for an arriving sample to land.
//
int pluginLoadBridges(const char* commaList, char* errorBuf, int errorBufSize)
{
  if (commaList == NULL)
    return 0;

  // Work on a copy (strtok_r modifies the string)
  char buf[1024];
  strncpy(buf, commaList, sizeof(buf) - 1);
  buf[sizeof(buf) - 1] = 0;

  char* saveptr = NULL;
  char* token   = strtok_r(buf, ",", &saveptr);

  while (token != NULL)
  {
    // Strip leading whitespace
    while (*token == ' ')
      token++;

    if (*token == 0)
    {
      token = strtok_r(NULL, ",", &saveptr);
      continue;
    }

    if (bridgeCount >= BRIDGES_MAX)
    {
      if (errorBuf != NULL)
        snprintf(errorBuf, errorBufSize, "too many bridge plugins (max %d)", BRIDGES_MAX);
      return -1;
    }

    char path[512];
    corPluginResolve(corPluginBaseDir(), "bridge", NULL, token, path, sizeof(path));

    char openErr[512];
    BridgeRegisterFunc registerFunc = (BridgeRegisterFunc) corPluginOpen(path, "bridgeRegister", openErr, sizeof(openErr));
    if (registerFunc == NULL)
    {
      //
      // A bridge named on the command line is an assertion being made NOW, so a
      // missing one is an error and the broker does not start. That is not in
      // conflict with a STORED Bridge object naming a plugin that is absent -
      // that is a record from the past, and it degrades to 'unavailable' rather
      // than vetoing a boot.
      //
      if (errorBuf != NULL)
      {
        if (strchr(token, '/') == NULL)
          snprintf(errorBuf, errorBufSize, "bridge plugin '%s' (%s): %s", token, path, openErr);
        else
          snprintf(errorBuf, errorBufSize, "bridge plugin '%s': %s", token, openErr);
      }
      return -1;
    }

    BridgeDriver* driverP = &bridges[bridgeCount];
    memset(driverP, 0, sizeof(BridgeDriver));

    //
    // ⭐ WHAT THIS BROKER SPEAKS, BEFORE THE PLUGIN WRITES A THING.
    //
    // The plugin fills in this struct, and the struct is OURS - allocated at
    // the size our header says. A plugin built against a newer contract knows
    // of slots that are not there, and without being told how much room it has
    // it would write them anyway, past the end of bridges[bridgeCount]. It
    // cannot be told by a parameter, because bridgeRegister takes one pointer
    // and nothing else, so it is told here and read back below as the PLUGIN's
    // own version. See the handshake note in BridgeDriver.h.
    //
    driverP->abiVersion = BRIDGE_ABI_VERSION;

    registerFunc(driverP);
    bridgeCount++;

    //
    // A mismatch is reported, not refused. The structs are append-only and the
    // broker owns their allocation, so an older plugin has simply left the
    // newer slots NULL - which is already how "not supported" is spelled.
    // Refusing to load would turn a working deployment red over a capability it
    // never asked for.
    //
    if (driverP->abiVersion != BRIDGE_ABI_VERSION)
      COR_I("bridge plugin '%s' was built against bridge ABI %d, this broker speaks %d - newer entry points will be treated as unsupported",
            (driverP->alias != NULL) ? driverP->alias : token, driverP->abiVersion, BRIDGE_ABI_VERSION);

    COR_I("bridge plugin loaded: %s (alias: %s)", path, (driverP->alias != NULL) ? driverP->alias : token);

    token = strtok_r(NULL, ",", &saveptr);
  }

  return 0;
}



// -----------------------------------------------------------------------------
//
// pluginArgsAdd -
//
void pluginArgsAdd(CorArg* argV)
{
  CorArgsStatus ks = corArgsAdd(argV);

  if (ks != CorArgsOk)
    COR_X(1, "a plugin's options: %s", corArgsStatus(ks));
}



// -----------------------------------------------------------------------------
//
// pluginSeparatedArgsAdd - a plugin's options under a separator line: "<kind> (<alias>) plugin options:"
//
static void pluginSeparatedArgsAdd(const char* kind, const char* alias, CorArg* argV, char* sepText, int sepTextSize, CorArg* sepArgV)
{
  if (alias != NULL)
    snprintf(sepText, sepTextSize, "%s (%s) plugin options:", kind, alias);
  else
    snprintf(sepText, sepTextSize, "%s plugin options:", kind);

  sepArgV[0]             = (CorArg) CORARGS_SEPARATOR(NULL);
  sepArgV[1]             = (CorArg) CORARGS_END;
  sepArgV[0].description = sepText;

  pluginArgsAdd(sepArgV);
  pluginArgsAdd(argV);
}



// -----------------------------------------------------------------------------
//
// pluginStoresLoad -
//
bool pluginStoresLoad(const char* dbName, const char* troeName)
{
  static char    dbSepText[128];
  static char    troeSepText[128];
  static CorArg  dbSepArgV[2];
  static CorArg  troeSepArgV[2];
  char           errBuf[1024];
  bool           error = false;

  //
  // DB plugin (dlopen + dbRegister, no DB connection yet)
  //
  if (pluginLoadDb(dbName, errBuf, sizeof(errBuf)) != 0)
  {
    fprintf(stderr, "%s\n", errBuf);
    error = true;
  }
  else if (db.args != NULL)
    pluginSeparatedArgsAdd("Database", db.alias, db.args, dbSepText, sizeof(dbSepText), dbSepArgV);

  //
  // TRoE plugin (dlopen + troeRegister, no connection yet)
  //
  if (pluginLoadTroe(troeName, errBuf, sizeof(errBuf)) != 0)
  {
    fprintf(stderr, "%s\n", errBuf);
    error = true;
  }
  else if (troe.args != NULL)
    pluginSeparatedArgsAdd("TRoE", troe.alias, troe.args, troeSepText, sizeof(troeSepText), troeSepArgV);

  corPluginArgUpdate("--database", "db/currentState");
  pluginTroeArgUpdate();

  return error;
}
