#
# FILE            makefile
#
# AUTHOR          Ken Zangelin
#
# Copyright 2026 Seamware
# SPDX-License-Identifier: Apache-2.0
#
# Convenience wrapper around CMake.
#
PREFIX         = /usr/local
BUILD_RELEASE  = BUILD_RELEASE
BUILD_DEBUG    = BUILD_DEBUG
BUILD_COVERAGE = BUILD_COVERAGE
#
# Functional-test coverage is measured PER CURRENT-STATE DB, because the two DB
# plugins take different paths through the broker and each leaves the other's
# plugin sources unexecuted. `make coverage` runs corDB, `make coverage DB=mongoc`
# runs mongoc, and each writes its own report - comparing a corDB run against a
# mongoc one is comparing two different measurements.
#
COV_DB        ?= $(if $(DB),$(DB),corDB)
COV_DIR        = coverage-$(COV_DB)
COV_REPORT     = $(COV_DIR)/index.html
COV_STATUS     = $(COV_DIR)/suite-status
COV_OTHER_DB   = $(if $(filter mongoc,$(COV_DB)),corDB,mongoc)
COV_PLUGIN_DIR = $(BUILD_COVERAGE)/plugins
COV_ETSI_DIR   = coverage-etsi
COV_LIBS       = corRest corNgsild corJsonld

# The sibling repos live NEXT TO this one - the CMake references and every lib
# include path resolve as ../<name>, so the layout is part of the build
# contract. Derive the parent from this makefile's own location rather than
# assuming a fixed path: that is what lets a checkout anywhere, CI included,
# build itself. All three stay overridable.
SIBLING_DIR   ?= $(abspath $(dir $(lastword $(MAKEFILE_LIST)))..)
CORTEST       ?= $(SIBLING_DIR)/corLibs/bin/corTest
# gcovr lives in the ETSI test-suite venv (gcov-15-aware). Override if needed.
GCOVR         ?= $(SIBLING_DIR)/ngsi-ld-test-suite/.venv/bin/gcovr

ifndef CPU_COUNT
	CPU_COUNT := $(shell nproc)
endif

PLUGIN_DIR = /opt/seamware/plugins
ETC_DIR    = /opt/seamware/etc

# contextSourceExtras (§ 5.2.40) — default opaque JSON config rendered on
# /info/sourceIdentity. Regenerated on every build with current version, git
# SHA and build timestamp; override at runtime via --contextSourceExtras.
# Read from the header the broker itself compiles in - two hand-maintained
# copies had already drifted (the binary said 0.3, this said 0.2.0, and the
# 0.2.0 is what /info/sourceIdentity was publishing).
CORAINE_VERSION   = $(shell sed -n 's/^#define CORAINE_VERSION "\(.*\)"/\1/p' src/app/coraine/coraineVersion.h)
CORAINE_GIT_SHA   = $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
CORAINE_BUILD_AT  = $(shell date -u +%Y-%m-%dT%H:%M:%SZ)

all:        release

# Sibling-repo libs we link against. `make di` here recurses into each and
# runs their own `make di`, which is a no-op when nothing changed and a
# rebuild+install when something did. Without this, editing a lib's source
# leaves the broker linking against a stale .a (silent — link succeeds
# against last-installed copy).
SIBLING_LIBS = corRest corNgsild corJsonld

libs:
	@for lib in $(SIBLING_LIBS); do \
	  $(MAKE) -C $(SIBLING_DIR)/$$lib di || exit 1; \
	done

#
# src/app/coraine/coraineStack.h - the resolved commit of every library linked in.
#
# GENERATED, never committed. The broker is largely library code, the cor* repos
# track main and the k-libs are pinned to release BRANCHES, so coraine's own sha
# answers only part of "what is this build". stackManifest.sh resolves the rest;
# this turns it into something getVersion can render.
#
# Regenerated on every build rather than cached: it is one `git rev-parse` per
# sibling, and a stale answer here is worse than no answer.
#
src/app/coraine/coraineStack.h: FORCE
	@{ echo '// GENERATED by the makefile from stackManifest.sh - do not edit, do not commit.'; 	   echo '#ifndef CORAINE_STACK_H_'; 	   echo '#define CORAINE_STACK_H_'; 	   echo ''; 	   echo 'static const char* const coraineStack[][2] ='; 	   echo '{'; 	   ./stackManifest.sh | while read -r lib sha; do printf '  { "%s", "%s" },\n' "$$lib" "$$sha"; done; 	   echo '  { NULL, NULL }'; 	   echo '};'; 	   echo ''; 	   echo '#endif  // CORAINE_STACK_H_'; 	 } > $@

release: libs etc/contextSourceExtras.json src/app/coraine/coraineStack.h
	cmake -B $(BUILD_RELEASE) -DCMAKE_BUILD_TYPE=Release
	cmake --build $(BUILD_RELEASE) -j$(CPU_COUNT)

debug: libs etc/contextSourceExtras.json src/app/coraine/coraineStack.h
	cmake -B $(BUILD_DEBUG) -DCMAKE_BUILD_TYPE=Debug
	cmake --build $(BUILD_DEBUG) -j$(CPU_COUNT)

clean:
	rm -rf $(BUILD_RELEASE) $(BUILD_DEBUG) $(BUILD_COVERAGE) coverage coverage-* $(COV_ETSI_DIR)

#
# The file is DATA, not source - nothing includes it and nothing compiles from
# it. The broker reads it at startup and renders it verbatim on
# /info/sourceIdentity (§ 5.2.40), so its content is a claim about the build
# that is running: version, commit, build time.
#
# Which is why it is regenerated unconditionally (FORCE) and is NOT in git. It
# used to be both committed and dependent on makefile+coraineVersion.h, so a
# fresh clone shipped whatever sha happened to be committed and `make` had no
# reason to correct it - the broker then announced a commit that was not the one
# serving the request.
#
FORCE:

etc/contextSourceExtras.json: FORCE
	@mkdir -p etc
	@printf '{\n  "version": "%s",\n  "gitSha": "%s",\n  "buildAt": "%s"\n}\n' \
	  "$(CORAINE_VERSION)" "$(CORAINE_GIT_SHA)" "$(CORAINE_BUILD_AT)" > $@

# install_from <build-dir> — copy broker + plugins + etc out of a build tree
define install_from
	mkdir -p $(PLUGIN_DIR)/db/currentState $(PLUGIN_DIR)/troe/temporal $(PLUGIN_DIR)/api $(ETC_DIR)
	cp -p $(1)/src/app/coraine/coraine                       $(PREFIX)/bin/
	cp -p $(1)/src/plugins/currentState/mongoc/mongoc.so       $(PLUGIN_DIR)/db/currentState/
	cp -p $(1)/src/plugins/currentState/corDB/corDB.so     $(PLUGIN_DIR)/db/currentState/
	cp -p $(1)/src/plugins/temporal/none/none.so               $(PLUGIN_DIR)/troe/temporal/
	cp -p $(1)/src/plugins/temporal/ramdb/ramdb.so             $(PLUGIN_DIR)/troe/temporal/
	cp -p $(1)/src/plugins/temporal/timescale/timescale.so     $(PLUGIN_DIR)/troe/temporal/
	cp -p $(1)/src/plugins/api/admin/admin.so                  $(PLUGIN_DIR)/api/
	cp -p etc/contextSourceExtras.json                         $(ETC_DIR)/
endef

install: etc/contextSourceExtras.json
	$(call install_from,$(BUILD_RELEASE))

install_debug: etc/contextSourceExtras.json
	$(call install_from,$(BUILD_DEBUG))

test:
	$(CORTEST)

coverage:
#
# The coverage tree is built from scratch, deliberately. gcov counters live in
# .gcno/.gcda files next to the objects, and nothing removes the ones belonging to
# a source that was renamed or deleted - gcovr then reports those vanished files as
# entirely unexecuted. That is not hypothetical: after corRamDB became corDB, a
# stale tree added ~700 phantom uncovered lines and moved the mongoc figure from
# 80.7% to 77.5%. A wrong coverage number is worse than none, and the rebuild is a
# couple of minutes against a twenty-minute suite.
#
	rm -rf $(BUILD_COVERAGE)
#
# Drop any previous verdict FIRST, before anything that can fail. A stale
# suite-status from an earlier run would otherwise outlive a build that never
# reached the suite, and the published page would report last week's verdict
# as this run's.
#
	@rm -f $(COV_STATUS)
#
# The libs are PART OF THE BROKER, so they belong in its coverage figure.
#
# corRest, corNgsild and corJsonld are static .a whole-archived into the binary -
# corNgsild alone is 31k lines, most of the NGSI-LD rules - and they are built by
# `make libs` with ordinary flags. Linked like that they carry no counters at all,
# so they were not reported as UNCOVERED, they were absent: neither numerator nor
# denominator. The published figure said "coraine/src" while looking like it said
# "the broker", and roughly half the C was outside it.
#
# So instrument them here, exactly as coverage-etsi has always done. They flush
# through the broker's own gcov runtime (whole-archived, no per-.so coverage link).
#
# The .gcno wipe is not redundant with `clean`: the libs' clean target removes
# objects, deps, .so and .a but NOT .gcno, and gcovr counts a .gcno whose source
# is gone as an entirely unexecuted file. Stale ones really do survive - a July
# coverage-etsi run left its .gcno sitting in corNgsild for seven weeks.
#
	@echo ">>> Instrumenting the libs ($(COV_LIBS)) - they are linked into the broker"
	@for d in $(COV_LIBS); do \
	   find $(SIBLING_DIR)/$$d -name '*.gcno' -delete; \
	   $(MAKE) -C $(SIBLING_DIR)/$$d clean >/dev/null && \
	   $(MAKE) -C $(SIBLING_DIR)/$$d DFLAGS="--coverage -O0 -Wno-error" lib$$d.a >/dev/null || exit 1; \
	 done
	cmake -B $(BUILD_COVERAGE) -DCMAKE_BUILD_TYPE=Coverage
	cmake --build $(BUILD_COVERAGE) -j$(CPU_COUNT)
#
# Stage the instrumented plugins in the INSTALLED layout. The harness composes
# $COR_PLUGIN_DIR/db/currentState/<name>.so, so without this it loads whatever
# sits in /opt/seamware - an ordinary build with no counters - and every plugin
# source then reports as unexecuted while the run appears to have covered it.
#
	@mkdir -p $(COV_PLUGIN_DIR)/db/currentState $(COV_PLUGIN_DIR)/troe/temporal $(COV_PLUGIN_DIR)/api
	@cp -p $(BUILD_COVERAGE)/src/plugins/currentState/*/*.so $(COV_PLUGIN_DIR)/db/currentState/
	@cp -p $(BUILD_COVERAGE)/src/plugins/temporal/*/*.so     $(COV_PLUGIN_DIR)/troe/temporal/
	@cp -p $(BUILD_COVERAGE)/src/plugins/api/*/*.so          $(COV_PLUGIN_DIR)/api/
	@find $(BUILD_COVERAGE) $(addprefix $(SIBLING_DIR)/,$(COV_LIBS)) -name '*.gcda' -delete
#
# COR_PLUGIN_DIR is how the HARNESS spells a plugin path (--database ...).
# SEAMWARE_PLUGIN_DIR is how the BROKER resolves a short name a test passes
# itself - `coraineStart --apiPlugins admin`. Without the second one the broker
# loads the installed admin.so, which carries no counters, and the whole admin
# plugin reads as 0% in a run whose tests exercise it.
#
#
# The suite's exit status is RECORDED, not discarded.
#
# It used to end in `|| true`, for a good reason - the report is this target's
# output, and a red test must not cost you the report. But swallowing the status
# outright meant a red suite was indistinguishable from a green one, and that is
# not theoretical: `usage.test` and `csource-reg-proactive-loop` failed in EVERY
# coverage run from 82775bc until 2026-08-26 and the job reported success each
# time. Nobody looks at a green job.
#
# So the status goes to a file, the report is built regardless, and the target
# fails at the END - after the report exists. The workflow's later steps run with
# `if: always()`, so the artifact and the Pages publish still happen; what changes
# is that the job goes red and the site says why.
#
	@mkdir -p $(COV_DIR)
	COR_BROKER=$(CURDIR)/$(BUILD_COVERAGE)/src/app/coraine/coraine \
	COR_PLUGIN_DIR=$(CURDIR)/$(COV_PLUGIN_DIR) \
	SEAMWARE_PLUGIN_DIR=$(CURDIR)/$(COV_PLUGIN_DIR) \
	$(CORTEST) -db $(COV_DB); echo $$? > $(COV_STATUS)
#
# The DB plugin that is NOT under test is excluded from the report. A corDB run
# cannot execute a line of mongoc.so and vice versa, so counting the other one
# as unexecuted measures the choice of DB rather than the state of the suite.
#
#
# --gcov-ignore-parse-errors: gcov occasionally reports a NEGATIVE hit count for
# a line in a threaded binary (GCC bug 68080), and gcovr treats that as fatal -
# a ten-minute run then ends with no report at all. coverage-etsi already passes
# this for the same reason.
#
# It needs gcovr >= 8.3 to do anything at all. In 8.2 the option is read only by
# the TEXT .gcov parser, while gcovr asks gcov for JSON by default - so the flag
# sat here inert until the nightly of 2026-08-25 died with it on the command line.
# The floor is pinned in corLibs/docker/Dockerfile.ci-nightly, which explains it.
#
# Do not remove the flag on the grounds that CMAKE_C_FLAGS_COVERAGE now carries
# -fprofile-update=atomic, and do not remove that on the grounds of this flag.
# They cover different halves: atomic counters stop the negative counts being
# PRODUCED, and on gcovr >= 8.3 a negative count without this flag does not fail -
# it drops the whole file from the report and exits 0, which is a silently short
# coverage figure.
#
#
# The root moves up to the sibling dir so the libs can be in the report at all,
# and the -f filters then say what "the broker" consists of: this repo's src plus
# the three libs archived into it. Everything else next door - corTest, corPlugin,
# the k-libs, other checkouts - stays out.
#
# ⚠️ This makes the percentage NOT comparable with anything recorded before
# 2026-09-01: the denominator roughly doubles. A drop against the old numbers is
# the measurement widening, not the suite regressing.
#
	$(GCOVR) --root $(SIBLING_DIR) \
	      --gcov-ignore-parse-errors=negative_hits.warn_once_per_file \
	      -f '$(CURDIR)/src/' \
	      $(foreach d,$(COV_LIBS),-f '$(SIBLING_DIR)/$(d)/') \
	      -e '.*/plugins/currentState/$(COV_OTHER_DB)/.*' \
	      --html-details $(COV_REPORT) --html-title "coraine coverage ($(COV_DB))" \
	      --print-summary \
	      $(BUILD_COVERAGE) $(addprefix $(SIBLING_DIR)/,$(COV_LIBS))
	@echo ""
	@echo "Coverage report ($(COV_DB)): file://$(CURDIR)/$(COV_REPORT)"
	@echo ""
	@echo "NOTE: $(COV_LIBS) are left INSTRUMENTED (--coverage -O0)."
	@echo "      Run 'make libs' before an ordinary build or a perf measurement."
#
# Now, and only now, the suite's verdict. The report exists either way.
#
	@status=$$(cat $(COV_STATUS)); \
	 if [ "$$status" != "0" ]; then \
	   echo ""; \
	   echo "*** The $(COV_DB) suite FAILED (corTest exited $$status)."; \
	   echo "*** The report above is real, but it measures a suite that is not passing."; \
	   exit $$status; \
	 fi

# Full ETSI-suite coverage: instrument the broker + NGSI-LD libs (corRest
# corNgsild corJsonld) + mongoc/timescale plugins, run the ETSI TP suite via
# etsiRun, then build an HTML report. The libs are static .a whole-archived
# into the broker, so they flush via the broker's gcov runtime (no per-.so
# coverage link needed); the plugin .so get --coverage from the Coverage build
# type (CMAKE_SHARED_LINKER_FLAGS).
coverage-etsi:
	@echo ">>> [1/6] Instrumenting NGSI-LD libs ($(COV_LIBS))..."
	@for d in $(COV_LIBS); do \
	   find ../$$d -name '*.gcno' -delete; \
	   $(MAKE) -C ../$$d clean >/dev/null && \
	   $(MAKE) -C ../$$d DFLAGS="--coverage -O0 -Wno-error" lib$$d.a || exit 1; \
	 done
	@echo ">>> [2/6] Building broker + plugins (Coverage)..."
	cmake -B $(BUILD_COVERAGE) -DCMAKE_BUILD_TYPE=Coverage
	cmake --build $(BUILD_COVERAGE) -j$(CPU_COUNT)
	@echo ">>> [3/6] Installing instrumented broker + plugins (etsiRun loads the installed ones)..."
	$(MAKE) install_from_coverage
	@echo ">>> [4/6] Wiping stale .gcda counters across build + lib trees..."
	@find $(BUILD_COVERAGE) $(addprefix ../,$(COV_LIBS)) -name '*.gcda' -delete
	@echo ">>> [5/6] Running the ETSI TP suite (etsiRun sw)..."
	@etsiRun sw || true
	@echo ">>> Stopping broker so gcov flushes .gcda (onSignal -> exit(0))..."
	@if [ -f /tmp/etsi-coraine.pid ]; then \
	   P=$$(cat /tmp/etsi-coraine.pid); \
	   kill "$$P" 2>/dev/null || true; \
	   for i in 1 2 3 4 5 6 7 8 9 10; do kill -0 "$$P" 2>/dev/null && sleep 1 || break; done; \
	 fi
	@echo ">>> [6/6] Generating coverage report..."
	@mkdir -p $(COV_ETSI_DIR)
	@$(GCOVR) --root $(SIBLING_DIR) --gcov-executable gcov \
	      --gcov-ignore-parse-errors=negative_hits.warn_once_per_file \
	      -f '$(CURDIR)/src/lib/' -f '$(CURDIR)/src/app/' \
	      -f '$(CURDIR)/src/plugins/currentState/mongoc/' \
	      -f '$(CURDIR)/src/plugins/temporal/timescale/' \
	      -f '$(CURDIR)/src/plugins/shared/' \
	      -f '$(SIBLING_DIR)/corRest/' -f '$(SIBLING_DIR)/corNgsild/' -f '$(SIBLING_DIR)/corJsonld/' \
	      --html-details $(COV_ETSI_DIR)/index.html --html-title "coraine ETSI Coverage" \
	      $(BUILD_COVERAGE) $(addprefix $(SIBLING_DIR)/,$(COV_LIBS))
	@echo ""
	@echo "ETSI coverage report: file://$(CURDIR)/$(COV_ETSI_DIR)/index.html"

install_from_coverage: etc/contextSourceExtras.json
	$(call install_from,$(BUILD_COVERAGE))

i:          release install
di:         debug install_debug
ci:         clean release install
cdi:        clean debug install_debug

.PHONY: all release debug clean install install_debug install_from_coverage test coverage coverage-etsi i di ci cdi libs
