//
// FILE            getBuild.c
//
// AUTHOR          Ken Zangelin
//
// Copyright 2026 Seamware
// SPDX-License-Identifier: Apache-2.0
//
// GET /build - what this deployment IS.
//
// Coraine can be compiled down to a subset of NGSI-LD, and a build with a
// feature compiled out is indistinguishable over the wire from a full one until
// something is asked for and answered 501. This is where it is asked.
//
// Three kinds of fact, and they are kept apart because they change at three
// different moments and an operator chasing "why does this deployment not do X"
// needs to know which one to go and look at:
//
//   features  - decided when the source was compiled. Nothing at run time moves
//               one. If REGISTRATIONS is false, no flag, plugin or restart
//               brings the registry API back; only another build does.
//   plugins   - `built` is decided at compile time too, but `loaded` is decided
//               at startup from a directory this binary does not own. A build
//               can carry a plugin that was never installed, and an install can
//               hold a plugin from a different build.
//   runtime   - decided on the command line, and changed by a restart. The
//               distinction that matters most here: a broker with REGISTRATIONS
//               compiled IN and --distributed off accepts registrations and
//               forwards nothing. The registry API and the forwarding are two
//               separate switches and this is the only place both are visible.
//
// Not the linked-library commits: those are GET /version's answer, and the
// question "what am I talking to" is a different one from "what can it do".
//
// Non-NGSI-LD, so the response bypasses @context expansion and compaction
// entirely (rawResponse), like /version. Deliberately NOT under /admin: the
// admin API is itself a compile-time feature, and an endpoint that reports what
// a build contains must not be one of the things a build can leave out.
//
#include <stdbool.h>                                 // bool

#include "kjson/KjNode.h"                            // KjNode
#include "kjson/kjBuilder.h"                         // kjObject, kjString, kjBoolean, kjArray, kjChildAdd

#include "corPlugin/corPlugin.h"                     // corPluginBaseDir
#include "corRest/CorRestState.h"                    // corRest
#include "corNgsild/corNgsild.h"                     // corNgsild (rawResponse)
#include "corNgsild/CorNgsild.h"                     // ldDistributed, ldSplitEntities, ldBrokerHttpEndpoint

#include "db/DbDriver.h"                             // db
#include "troe/TroeDriver.h"                         // troe
#include "plugin/ApiPlugin.h"                        // apiPlugins, apiPluginCount

#include "coraineVersion.h"                          // CORAINE_VERSION   (-Isrc/app/coraine)
#include "coraineBuild.h"                            // CORAINE_GIT_SHA, CORAINE_BUILT_AT - GENERATED, see the makefile
#include "coraineFeatures.h"                         // coraineFeatures, coraineBuiltPlugins
#include "serviceRoutines/getBuild.h"                // Own interface



// -----------------------------------------------------------------------------
//
// loadedPlugin - one { alias, version } object, or a JSON null if none is loaded
//
// A null rather than an omitted member: "no TRoE plugin is loaded" is an answer,
// and a member that simply is not there reads as "this broker is too old to say".
//
static KjNode* loadedPlugin(const char* name, const char* alias, const char* version)
{
  if (alias == NULL)
    return kjNull(corRest.kjsonP, name);

  KjNode* objP = kjObject(corRest.kjsonP, name);

  kjChildAdd(objP, kjString(corRest.kjsonP, "alias",   alias));
  kjChildAdd(objP, kjString(corRest.kjsonP, "version", (version != NULL) ? version : "unknown"));

  return objP;
}



// -----------------------------------------------------------------------------
//
// getBuild -
//
bool getBuild(void)
{
  KjNode* body = kjObject(corRest.kjsonP, NULL);

  kjChildAdd(body, kjString(corRest.kjsonP, "product", "coraine"));
  kjChildAdd(body, kjString(corRest.kjsonP, "version", CORAINE_VERSION));

  //
  // Where this binary came from. The sha and the timestamp are regenerated by
  // the makefile on every build; the flavour and the compiler come from cmake.
  //
  KjNode* buildP = kjObject(corRest.kjsonP, "build");

  kjChildAdd(buildP, kjString(corRest.kjsonP, "gitSha",   CORAINE_GIT_SHA));
  kjChildAdd(buildP, kjString(corRest.kjsonP, "builtAt",  CORAINE_BUILT_AT));
  kjChildAdd(buildP, kjString(corRest.kjsonP, "type",     CORAINE_BUILD_TYPE));
  kjChildAdd(buildP, kjString(corRest.kjsonP, "compiler", CORAINE_BUILD_COMPILER));

  //
  // Which HTTP server this build carries. Not in `features` - that object
  // answers "is this capability present", and the HTTP server is always
  // present; what varies is WHICH ONE, and a boolean cannot say that.
  //
  kjChildAdd(buildP, kjString(corRest.kjsonP, "httpServer", CORAINE_HTTP_SERVER));
  kjChildAdd(body, buildP);

  //
  // Every feature with its value, never an omitted name: absent would not
  // distinguish "off" from "this broker predates the name".
  //
  KjNode* featuresP = kjObject(corRest.kjsonP, "features");

  for (int ix = 0; coraineFeatures[ix].name != NULL; ix++)
    kjChildAdd(featuresP, kjBoolean(corRest.kjsonP, coraineFeatures[ix].name, coraineFeatures[ix].on));

  kjChildAdd(body, featuresP);

  KjNode* pluginsP = kjObject(corRest.kjsonP, "plugins");

  kjChildAdd(pluginsP, kjString(corRest.kjsonP, "directory", corPluginBaseDir()));

  //
  // 'built' is what the cmake run that produced this binary also produced -
  // NOT what is installed in the directory above. The two differ often enough
  // that saying which is which is the whole value of the member.
  //
  KjNode* builtP = kjArray(corRest.kjsonP, "built");

  for (int ix = 0; coraineBuiltPlugins[ix].kind != NULL; ix++)
  {
    KjNode* p = kjObject(corRest.kjsonP, NULL);

    kjChildAdd(p, kjString(corRest.kjsonP, "kind", coraineBuiltPlugins[ix].kind));
    kjChildAdd(p, kjString(corRest.kjsonP, "name", coraineBuiltPlugins[ix].name));
    kjChildAdd(builtP, p);
  }

  kjChildAdd(pluginsP, builtP);

  KjNode* loadedP = kjObject(corRest.kjsonP, "loaded");

  kjChildAdd(loadedP, loadedPlugin("currentState", db.alias,   db.version));
  kjChildAdd(loadedP, loadedPlugin("temporal",     troe.alias, troe.version));

  KjNode* apiP = kjArray(corRest.kjsonP, "api");

  for (int ix = 0; ix < apiPluginCount; ix++)
  {
    KjNode* p = kjObject(corRest.kjsonP, NULL);

    kjChildAdd(p, kjString(corRest.kjsonP, "alias",   apiPlugins[ix].alias));
    kjChildAdd(p, kjString(corRest.kjsonP, "version", (apiPlugins[ix].version != NULL) ? apiPlugins[ix].version : "unknown"));
    kjChildAdd(apiP, p);
  }

  kjChildAdd(loadedP, apiP);
  kjChildAdd(pluginsP, loadedP);
  kjChildAdd(body, pluginsP);

  //
  // The command-line half. Only the settings that change what a CLIENT gets -
  // not the tuning (pool sizes, timeouts), which changes how fast it gets it.
  //
  KjNode* runtimeP = kjObject(corRest.kjsonP, "runtime");

  kjChildAdd(runtimeP, kjBoolean(corRest.kjsonP, "distributed",   ldDistributed));
  kjChildAdd(runtimeP, kjBoolean(corRest.kjsonP, "splitEntities", ldSplitEntities));
  kjChildAdd(runtimeP, kjString(corRest.kjsonP,  "httpEndpoint",  (ldBrokerHttpEndpoint != NULL) ? ldBrokerHttpEndpoint : ""));
  kjChildAdd(body, runtimeP);

  corNgsild.rawResponse      = true;
  corRest.out.responseTree   = body;
  corRest.out.httpStatusCode = 200;

  return true;
}
