//
// FILE            getBuild.c
//
// AUTHOR          Ken Zangelin
//
// Copyright 2026 Seamware
// SPDX-License-Identifier: Apache-2.0
//
// GET /build - what this deployment IS.
//
// Coraine can be compiled down to a subset of NGSI-LD, and a build with a
// feature compiled out is indistinguishable over the wire from a full one until
// something is asked for and answered 501. This is where it is asked.
//
// Three kinds of fact, and they are kept apart because they change at three
// different moments and an operator chasing "why does this deployment not do X"
// needs to know which one to go and look at:
//
//   features  - decided when the source was compiled. Nothing at run time moves
//               one. If REGISTRATIONS is false, no flag, plugin or restart
//               brings the registry API back; only another build does.
//   plugins   - `built` is decided at compile time too, but `loaded` is decided
//               at startup from a directory this binary does not own. A build
//               can carry a plugin that was never installed, and an install can
//               hold a plugin from a different build.
//   runtime   - decided on the command line, and changed by a restart. The
//               distinction that matters most here: a broker with REGISTRATIONS
//               compiled IN and --distributed off accepts registrations and
//               forwards nothing. The registry API and the forwarding are two
//               separate switches and this is the only place both are visible.
//
// Not the linked-library commits: those are GET /version's answer, and the
// question "what am I talking to" is a different one from "what can it do".
//
// Non-NGSI-LD, so the response bypasses @context expansion and compaction
// entirely (rawResponse), like /version. Deliberately NOT under /admin: the
// admin API is itself a compile-time feature, and an endpoint that reports what
// a build contains must not be one of the things a build can leave out.
//
#include <stdbool.h>                                 // bool

#include "corTree/CorNode.h"                         // CorNode
#include "corTree/corTreeBuilder.h"                  // corTreeObject, corTreeString, corTreeBoolean, corTreeArray, corTreeChildAdd

#include "corPlugin/corPlugin.h"                     // corPluginBaseDir
#include "corRest/CorRestState.h"                    // corRest
#include "corNgsild/corNgsild.h"                     // corNgsild (rawResponse)
#include "corNgsild/CorNgsild.h"                     // ldDistributed, ldSplitEntities, ldBrokerHttpEndpoint

#include "db/DbDriver.h"                             // db
#include "troe/TroeDriver.h"                         // troe
#include "plugin/ApiPlugin.h"                        // apiPlugins, apiPluginCount

#include "coraineVersion.h"                          // CORAINE_VERSION   (-Isrc/app/coraine)
#include "coraineBuild.h"                            // CORAINE_GIT_SHA, CORAINE_BUILT_AT - GENERATED, see the makefile
#include "coraineFeatures.h"                         // coraineFeatures, coraineBuiltPlugins
#include "serviceRoutines/getBuild.h"                // Own interface



// -----------------------------------------------------------------------------
//
// loadedPlugin - one { alias, version } object, or a JSON null if none is loaded
//
// A null rather than an omitted member: "no TRoE plugin is loaded" is an answer,
// and a member that simply is not there reads as "this broker is too old to say".
//
static CorNode* loadedPlugin(const char* name, const char* alias, const char* version)
{
  if (alias == NULL)
    return corTreeNull(corRest.kallocP, name);

  CorNode* objP = corTreeObject(corRest.kallocP, name);

  corTreeChildAdd(objP, corTreeString(corRest.kallocP, "alias", alias));
  corTreeChildAdd(objP, corTreeString(corRest.kallocP, "version", (version != NULL) ? version : "unknown"));

  return objP;
}



// -----------------------------------------------------------------------------
//
// getBuild -
//
bool getBuild(void)
{
  CorNode* body = corTreeObject(corRest.kallocP, NULL);

  corTreeChildAdd(body, corTreeString(corRest.kallocP, "product", "coraine"));
  corTreeChildAdd(body, corTreeString(corRest.kallocP, "version", CORAINE_VERSION));

  //
  // Where this binary came from. The sha and the timestamp are regenerated by
  // the makefile on every build; the flavour and the compiler come from cmake.
  //
  CorNode* buildP = corTreeObject(corRest.kallocP, "build");

  corTreeChildAdd(buildP, corTreeString(corRest.kallocP, "gitSha", CORAINE_GIT_SHA));
  corTreeChildAdd(buildP, corTreeString(corRest.kallocP, "builtAt", CORAINE_BUILT_AT));
  corTreeChildAdd(buildP, corTreeString(corRest.kallocP, "type", CORAINE_BUILD_TYPE));
  corTreeChildAdd(buildP, corTreeString(corRest.kallocP, "compiler", CORAINE_BUILD_COMPILER));

  //
  // Which HTTP server this build carries. Not in `features` - that object
  // answers "is this capability present", and the HTTP server is always
  // present; what varies is WHICH ONE, and a boolean cannot say that.
  //
  corTreeChildAdd(buildP, corTreeString(corRest.kallocP, "httpServer", CORAINE_HTTP_SERVER));
  corTreeChildAdd(body, buildP);

  //
  // Every feature with its value, never an omitted name: absent would not
  // distinguish "off" from "this broker predates the name".
  //
  CorNode* featuresP = corTreeObject(corRest.kallocP, "features");

  for (int ix = 0; coraineFeatures[ix].name != NULL; ix++)
    corTreeChildAdd(featuresP, corTreeBoolean(corRest.kallocP, coraineFeatures[ix].name, coraineFeatures[ix].on));

  corTreeChildAdd(body, featuresP);

  CorNode* pluginsP = corTreeObject(corRest.kallocP, "plugins");

  corTreeChildAdd(pluginsP, corTreeString(corRest.kallocP, "directory", corPluginBaseDir()));

  //
  // 'built' is what the cmake run that produced this binary also produced -
  // NOT what is installed in the directory above. The two differ often enough
  // that saying which is which is the whole value of the member.
  //
  CorNode* builtP = corTreeArray(corRest.kallocP, "built");

  for (int ix = 0; coraineBuiltPlugins[ix].kind != NULL; ix++)
  {
    CorNode* p = corTreeObject(corRest.kallocP, NULL);

    corTreeChildAdd(p, corTreeString(corRest.kallocP, "kind", coraineBuiltPlugins[ix].kind));
    corTreeChildAdd(p, corTreeString(corRest.kallocP, "name", coraineBuiltPlugins[ix].name));
    corTreeChildAdd(builtP, p);
  }

  corTreeChildAdd(pluginsP, builtP);

  CorNode* loadedP = corTreeObject(corRest.kallocP, "loaded");

  corTreeChildAdd(loadedP, loadedPlugin("currentState", db.alias, db.version));
  corTreeChildAdd(loadedP, loadedPlugin("temporal", troe.alias, troe.version));

  CorNode* apiP = corTreeArray(corRest.kallocP, "api");

  for (int ix = 0; ix < apiPluginCount; ix++)
  {
    CorNode* p = corTreeObject(corRest.kallocP, NULL);

    corTreeChildAdd(p, corTreeString(corRest.kallocP, "alias", apiPlugins[ix].alias));
    corTreeChildAdd(p, corTreeString(corRest.kallocP, "version", (apiPlugins[ix].version != NULL) ? apiPlugins[ix].version : "unknown"));
    corTreeChildAdd(apiP, p);
  }

  corTreeChildAdd(loadedP, apiP);
  corTreeChildAdd(pluginsP, loadedP);
  corTreeChildAdd(body, pluginsP);

  //
  // The command-line half. Only the settings that change what a CLIENT gets -
  // not the tuning (pool sizes, timeouts), which changes how fast it gets it.
  //
  CorNode* runtimeP = corTreeObject(corRest.kallocP, "runtime");

  corTreeChildAdd(runtimeP, corTreeBoolean(corRest.kallocP, "distributed", ldDistributed));
  corTreeChildAdd(runtimeP, corTreeBoolean(corRest.kallocP, "splitEntities", ldSplitEntities));
  corTreeChildAdd(runtimeP, corTreeString(corRest.kallocP, "httpEndpoint", (ldBrokerHttpEndpoint != NULL) ? ldBrokerHttpEndpoint : ""));
  corTreeChildAdd(body, runtimeP);

  corNgsild.rawResponse      = true;
  corRest.out.responseTree   = body;
  corRest.out.httpStatusCode = 200;

  return true;
}
