#!/usr/bin/env bash
#
# vendor-libs.sh — stage the Cor-Libs into the Docker build context.
#
# WHY THIS EXISTS: the k-libs (gitlab.com/kzangeli) are cloned by the image
# itself, at the release branches klib-pins names. The Cor-Libs
# (github.com/SEAMWARE) are NOT cloned — they are exported from the local clones
# with `git archive HEAD` and copied in.
#
# They were private when this was written, so there was no choice; they are
# public now and the reason is a different one. A clone would build whatever
# `main` happens to be at that moment, which is not what the developer running
# `docker build` is looking at. Vendoring ships the tree they have COMMITTED,
# and MANIFEST.txt records the sha that went in.
#
# `git archive HEAD` gives exactly the committed tree: no .git, no build
# artifacts, no uncommitted work. Anything you have not committed will NOT be in
# the image — the manifest flags it when that happens.
#
# Usage (from the repo root, before docker build):
#   ./docker/vendor-libs.sh
#   docker build -f docker/Dockerfile -t coraine:local .
#
# Alternative if you would rather clone from GitHub inside the build: pass a
# token as a BuildKit secret and swap the untar step for a clone. Vendoring is
# the default because it needs no secret and no repo-visibility change.
#
# Copyright 2026 Seamware
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

BASE="${BASE:-$HOME/git}"
OUT="$(cd "$(dirname "$0")" && pwd)/vendor"
# corHttp is here even though the default build does not LINK it: corLibs'
# umbrella makefile builds every Cor-Lib, so a missing directory fails the image
# build at `make -C corLibs di` rather than at the link. Which is how it was
# found.
LIBS=(corPlugin corHttp corRest corJsonld corNgsild corTest corLibs)

rm -rf "$OUT"
mkdir -p "$OUT"
MANIFEST="$OUT/MANIFEST.txt"

{
  echo "# Cor-Libs vendored into the coraine image"
  echo "# generated by docker/vendor-libs.sh from committed HEADs in $BASE"
  echo
} > "$MANIFEST"

for lib in "${LIBS[@]}"; do
    repo="$BASE/$lib"
    if [ ! -d "$repo/.git" ]; then
        echo "vendor-libs.sh: no git clone at $repo" >&2
        exit 1
    fi

    branch=$(git -C "$repo" rev-parse --abbrev-ref HEAD)
    sha=$(git -C "$repo" rev-parse HEAD)
    # Tracked modifications only — untracked build junk is irrelevant here.
    dirty=$(git -C "$repo" status --porcelain --untracked-files=no | wc -l)

    git -C "$repo" archive --format=tar --prefix="$lib/" HEAD -o "$OUT/$lib.tar"

    note=""
    if [ "$dirty" -gt 0 ]; then
        note="  <-- $dirty uncommitted change(s) NOT included"
    fi
    printf '%-10s %-24s %s%s\n' "$lib" "$branch" "$sha" "$note" >> "$MANIFEST"
done

#
# The k-lib pins live in corLibs and are the single source of truth. Stage a
# plain copy next to the tarballs so the Dockerfile can COPY it on its own,
# EARLY, without unpacking corLibs first: the pins change rarely and the
# vendored libs change constantly, so keeping them separate layers is what
# stops every lib commit from re-cloning the whole k-lib set.
#
git -C "$BASE/corLibs" show HEAD:klib-pins > "$OUT/klib-pins"

echo "vendored $(printf '%s ' "${LIBS[@]}")+ klib-pins -> $OUT"
cat "$MANIFEST"
echo
cat "$OUT/klib-pins"
