#!/bin/bash
#
# FILE            sanSetup.sh
#
# AUTHOR          Ken Zangelin
#
# Copyright 2026 Seamware
# SPDX-License-Identifier: Apache-2.0
#
# sanSetup.sh <dir> [<bin dir>] - the tools of a sanitizer run (AddressSanitizer + LeakSanitizer +
# UndefinedBehaviorSanitizer), written into <dir>:
#
#   gcc-san          gcc with -fsanitize=address,undefined -fno-omit-frame-pointer -O1 -g appended - the
#                    compiler of the libs (CC=) and of the broker (cmake reads CC from the environment)
#   sanPreload.so    dlclose() as a no-op: a plugin stays mapped until the process exits, so a leak
#                    report names the plugin's frames instead of "<unknown module>"
#   coraine          the broker under the sanitizers - corTest's COR_BROKER
#   coraine-import   the importer, the same way - corTest's COR_IMPORT
#
# <bin dir> is where the sanitized coraine and coraine-import are installed (default /usr/local/bin,
# the makefile's PREFIX). The wrappers exec them, so the pid corTest records is the broker's own.
#
# A run: the reports go to $SAN_REPORT_DIR (default /tmp/san-reports):
#
#   asan.<pid>       an ASan or LSan report (log_path)
#   ubsan.<pid>      a UBSan report, where UBSan honours log_path
#   stderr.<pid>     the UBSan reports of the broker's stderr - with gcc, UBSan inside an ASan process
#                    prints to stderr whatever log_path says, and a broker's stderr is the test's
#                    /tmp/coraine.<role>.log, overwritten by the next start
#   pids             one line per process: pid, time, the command that started it (the test section)
#
# test/sanitizer/sanReport.py <report dir> reads them. doc/testing.md, "Sanitizers".
#
set -euo pipefail

DIR=${1:?usage: sanSetup.sh <dir> [<bin dir>]}
BIN_DIR=${2:-/usr/local/bin}
HERE=$(cd "$(dirname "$0")" && pwd)
mkdir -p "$DIR"
DIR=$(cd "$DIR" && pwd)

cat > "$DIR/gcc-san" <<'EOF'
#!/bin/sh
exec gcc "$@" -fsanitize=address,undefined -fno-omit-frame-pointer -O1 -g
EOF
chmod +x "$DIR/gcc-san"

gcc -shared -fPIC -O2 -o "$DIR/sanPreload.so" "$HERE/sanPreload.c"

LIBASAN=$(gcc -print-file-name=libasan.so)
[ -e "$LIBASAN" ] || { echo "sanSetup.sh: no libasan.so ($LIBASAN)" >&2; exit 1; }

#
# One wrapper per binary. The sanitizer options reach the broker ONLY (the exec at the end) - not tee,
# date or tr. abort_on_error=0: an ASan error still ends the process (halt_on_error), with exit code 1
# rather than a core. allow_user_segv_handler=1: the broker's own crash report (crash_report_*.test)
# runs on a fatal signal, as it does outside the sanitizers. exec -a: argv[0] is the plain name, as
# when corTest runs `coraine` from PATH - the crash report prints the command line.
#
wrapper()
{
  local name=$1
  cat > "$DIR/$name" <<EOF
#!/bin/bash
# The sanitized $name - generated by test/sanitizer/sanSetup.sh
R=\${SAN_REPORT_DIR:-/tmp/san-reports}; mkdir -p "\$R"
echo "\$\$ \$(date +%T.%N) [\$(tr '\\0' ' ' < /proc/\$PPID/cmdline)] \$*" >> "\$R/pids"
exec 2> >(awk -v f="\$R/stderr.\$\$" '{ print; fflush() } /runtime error:/ { n = 30 } n > 0 { print >> f; fflush(f); n-- }' >&2)
ASAN_OPTIONS=detect_leaks=1:abort_on_error=0:log_path=\$R/asan:allocator_may_return_null=1:allow_user_segv_handler=1 \\
UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=0:log_path=\$R/ubsan \\
LSAN_OPTIONS=suppressions=$HERE/lsan.supp:print_suppressions=0 \\
LD_PRELOAD=$LIBASAN:$DIR/sanPreload.so \\
exec -a $name "$BIN_DIR/$name" "\$@"
EOF
  chmod +x "$DIR/$name"
}

wrapper coraine
wrapper coraine-import

echo "sanSetup.sh: $DIR/{gcc-san,sanPreload.so,coraine,coraine-import} (binaries from $BIN_DIR, libasan $LIBASAN)"
