//
// FILE            dbPluginAbi.c
//
// AUTHOR          Ken Zangelin
//
// Copyright 2026 Seamware
// SPDX-License-Identifier: Apache-2.0
//
// The DB / TRoE plugin interface stamp, the plugin's side - see dbPluginAbi.h
//
#define _GNU_SOURCE                                       // RTLD_DEFAULT, dladdr

#include <dlfcn.h>                                        // dlsym, dladdr, RTLD_DEFAULT
#include <stdio.h>                                        // fprintf, stderr
#include <stdlib.h>                                       // exit
#include <string.h>                                       // strcmp
#include <unistd.h>                                       // readlink

#include "dbAbiStamp.h"                                   // DB_ABI_STAMP - generated by tools/dbAbiStamp.sh
#include "shared/dbPluginAbi.h"                           // Own interface



// -----------------------------------------------------------------------------
//
// dbPluginAbi - exported: the broker reads it with dlsym before it calls the register function
//
__attribute__((visibility("default"), used)) const char dbPluginAbi[] = DB_ABI_STAMP;



// -----------------------------------------------------------------------------
//
// stamp - the same stamp, not interposable: the comparison below is with THIS plugin's own, whatever else
// in the process exports a dbPluginAbi
//
static const char stamp[] = DB_ABI_STAMP;



// -----------------------------------------------------------------------------
//
// dbPluginAbiBrokerCheck -
//
void dbPluginAbiBrokerCheck(const char* kind)
{
  //
  // RTLD_DEFAULT: the global scope - the broker executable (linked -rdynamic) first
  //
  const char* brokerStamp = (const char*) dlsym(RTLD_DEFAULT, "coraineDbAbi");

  if ((brokerStamp != NULL) && (strcmp(brokerStamp, stamp) == 0))
    return;

  const char* pluginPath = "?";
  Dl_info     info;

  if ((dladdr(stamp, &info) != 0) && (info.dli_fname != NULL))
    pluginPath = info.dli_fname;

  char     brokerPath[512];
  ssize_t  len = readlink("/proc/self/exe", brokerPath, sizeof(brokerPath) - 1);

  if (len <= 0)
    len = snprintf(brokerPath, sizeof(brokerPath), "?");
  brokerPath[len] = 0;

  if (brokerStamp == NULL)
    fprintf(stderr, "%s plugin '%s' refuses the broker '%s': the broker is older than the plugin - it has no DB plugin interface stamp; a plugin built against another DB plugin interface corrupts memory\n",
            kind, pluginPath, brokerPath);
  else
    fprintf(stderr, "%s plugin '%s' refuses the broker '%s': the broker was built against another DB plugin interface; a plugin built against another DB plugin interface corrupts memory\n",
            kind, pluginPath, brokerPath);

  fprintf(stderr, "  plugin's interface stamp: %s\n", stamp);
  fprintf(stderr, "  broker's interface stamp: %.32s\n", (brokerStamp != NULL) ? brokerStamp : "none - built before the check");
  fprintf(stderr, "  rebuild the plugin against this broker's source, or install matching versions of the broker and its plugins\n");

  exit(1);
}
