#!/bin/bash
#
# dbAbiStamp.sh - the stamp of the DB / TRoE plugin interface: a hash of the headers the broker and its
# DB and TRoE plugins compile against (doc/plugin-architecture.md, "The DB plugin interface stamp").
#
# A DB or TRoE plugin shares structs with the broker by layout - DbDriver, DbQueryFilter, Tenant,
# TroeDriver, CorNode, ... - and a plugin built against other headers than its broker reads and writes
# them at the wrong offsets. The broker exports this stamp (coraineDbAbi), every DB / TRoE plugin exports
# its own (dbPluginAbi), and each side refuses the other when they differ.
#
# The headers: the interface headers below (SEEDS) and every header they include with #include "...",
# found in the coraine source (src/lib) or beside it (the Cor-Libs), followed to the end. System headers
# (<...>) are not followed. Each header is hashed with its comments stripped (gcc -fpreprocessed: no
# macro is expanded, no #include followed) and its whitespace collapsed: a comment edit leaves the stamp
# as it was, a change to any declaration changes it.
#
# Usage:
#   dbAbiStamp.sh                  the stamp (16 hex digits)
#   dbAbiStamp.sh --list           the headers it covers, one per line, as found
#   dbAbiStamp.sh --header <file>  <file> as a C header defining DB_ABI_STAMP - rewritten only when the
#                                  stamp changed, so what includes it recompiles only then
#
# Run by coraine's CMake (the generated dbAbiStamp.h) and by corDB's makefile - the one definition of
# the stamp for both sides.
#
# Copyright 2026 Seamware
# SPDX-License-Identifier: Apache-2.0
#
set -u
set -o pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
CORAINE=$(dirname "$HERE")
SRC_LIB="$CORAINE/src/lib"
COR_LIBS=${COR_LIBS:-$(dirname "$CORAINE")}

SEEDS="db/DbDriver.h db/DbQueryFilter.h db/Tenant.h ha/HaEvent.h ha/haInit.h troe/TroeDriver.h"

LIST=no
HEADER=
if [ "${1:-}" == "--list" ] && [ $# == 1 ]
then
  LIST=yes
elif [ "${1:-}" == "--header" ] && [ $# == 2 ]
then
  HEADER=$2
elif [ $# != 0 ]
then
  echo "usage: $0 [--list | --header <file>]" >&2
  exit 2
fi

#
# headerFind <name> - the file a #include "<name>" resolves to: coraine's src/lib, then the Cor-Libs
#
headerFind()
{
  if [ -f "$SRC_LIB/$1" ]
  then
    echo "$SRC_LIB/$1"
  elif [ -f "$COR_LIBS/$1" ]
  then
    echo "$COR_LIBS/$1"
  else
    return 1
  fi
}

#
# The closure, breadth first from the seeds - a fixed order, so the same headers give the same stamp
#
declare -A seen
queue=($SEEDS)
headers=()
i=0

while [ $i -lt ${#queue[@]} ]
do
  name=${queue[$i]}
  i=$((i + 1))

  [ -n "${seen[$name]:-}" ] && continue
  seen[$name]=1

  path=$(headerFind "$name")
  if [ $? != 0 ]
  then
    echo "dbAbiStamp.sh: '$name' not found in $SRC_LIB or $COR_LIBS" >&2
    exit 1
  fi

  headers+=("$name:$path")

  for inc in $(sed -n 's/^[ \t]*#[ \t]*include[ \t]*"\([^"]*\)".*/\1/p' "$path")
  do
    queue+=("$inc")
  done
done

if [ $LIST == yes ]
then
  for h in "${headers[@]}"
  do
    echo "${h#*:}"
  done
  exit 0
fi

#
# Each header under its include name (not its path - the checkout's location is no part of the
# interface), comments stripped, whitespace collapsed, empty lines dropped
#
stamp=$(for h in "${headers[@]}"
        do
          echo "== ${h%%:*}"
          gcc -x c -fpreprocessed -dD -E -P "${h#*:}" || exit 1
        done | tr -s ' \t' '  ' | sed -e 's/^ //' -e 's/ $//' -e '/^$/d' | sha256sum | cut -c1-16) || exit 1

if [ -z "$HEADER" ]
then
  echo "$stamp"
  exit 0
fi

content="// GENERATED by coraine's tools/dbAbiStamp.sh - do not edit, do not commit.
#ifndef DB_ABI_STAMP_H_
#define DB_ABI_STAMP_H_
#define DB_ABI_STAMP \"$stamp\"
#endif  // DB_ABI_STAMP_H_"

if [ "$(cat "$HEADER" 2>/dev/null)" != "$content" ]
then
  mkdir -p "$(dirname "$HEADER")" && echo "$content" > "$HEADER" || exit 1
fi
